parameters:
    admin.route.path_prefix:  /admin
    admin.route.route_prefix: admin

services:
    admin.pool:
        public: true
        class: App\AdminBundle\Admin\Pool
        arguments:
            - "@service_container"

    admin.route_generator:
        public: true
        class: App\AdminBundle\Route\RouteGenerator
        arguments:
            - "%admin.route.path_prefix%"
            - "%admin.route.route_prefix%"

#    twig.admin_extension:
#        public: true
#        class: App\AdminBundle\Twig\AdminExtension
#        arguments:
#            - "@router"
#            - "@admin.route_generator"
#            - "@admin.pool"
#        tags:
#            - { name: twig.extension }
#
#    twig.admin_menu_extension:
#        public: true
#        class: App\AdminBundle\Twig\AdminMenuExtension
#        tags:
#            - { name: twig.extension }
