parameters:
    admin.route.path_prefix:  /admin
    admin.route.route_prefix: admin
    admin.content.animate:    false

services:
    admin.pool:
        public: true
        class: AdminBundle\Admin\Pool
        arguments:
            - "@service_container"

    admin.route_generator:
        public: true
        class: AdminBundle\Route\RouteGenerator
        arguments:
            - "%admin.route.path_prefix%"
            - "%admin.route.route_prefix%"

    twig.admin_extension:
        public: true
        class: AdminBundle\Twig\AdminExtension
        arguments:
            - "@router"
            - "@admin.route_generator"
            - "@admin.pool"
            - "@parameter_bag"
        tags:
            - { name: twig.extension }

    twig.admin_menu_extension:
        public: true
        class: AdminBundle\Twig\AdminMenuExtension
        tags:
            - { name: twig.extension }
